name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      goos:
        description: 'Target OS (e.g., linux, windows)'
        required: true
        default: 'linux'
      goarch:
        description: 'Target Architecture (e.g., amd64, arm64)'
        required: true
        default: 'amd64'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        goos: [linux]
        goarch: [amd64]

    name: Build artifacts
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.23
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
    outputs:
      tag_name: ${{ steps.extract_branch.outputs.tag }}
    steps:
      - run: git config --global --add safe.directory ${{ github.workspace }}
      - uses: actions/checkout@v4

      - name: Fetch IPInfo GeoIP Database
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
        run: |
          rm pkg/geoip/geoip.db
          wget -qO pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --single-target --clean --skip=validate

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-${{ env.GOOS }}-${{ env.GOARCH }}
          path: |
            ./dist/*/*
